openapi: 3.1.0
info:
  title: Validation and Conversion Service API
  version: 1.1.5
  description: |-
    This API documentation describes the publicly available Validation and
    Conversion Service of Skribble.
  license:
    name: Apache 2.0
    identifier: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.skribble.com/en-eu/terms-of-use/
  contact:
    name: Skribble Engineering
    url: https://skribble.com
    email: info@skribble.com
servers:
  - url: https://document-validation.skribble.com/v1
    description: Production - Switzerland
  - url: https://document-validation.skribble.de/v1
    description: Production - Germany
  - url: https://document-validation.scribital.com/v1
    description: Staging - Switzerland
  - url: https://document-validation.scribital.de/v1
    description: Staging - Germany
security: []
tags:
  - name: Access
    description: Endpoints for authentication, authorization, and user access management.
  - name: Validation
    description: Endpoints to validate documents, data formats, and signatures.
  - name: Additional Information
    description: Endpoints providing extra metadata or supplementary details for documents.
  - name: Reports
    description: Endpoints for generating, retrieving, and managing reports related to document processing.
  - name: Tooling
    description: Utility endpoints and tools that assist with document handling or integration.
  - name: Billing and Credits
    description: Endpoints for managing account credits, billing information, and payment operations.
paths:
  /access/login:
    post:
      operationId: postAccessLogin
      tags:
        - Access
      summary: Sign in to receive an access token using JSON to submit credentials
      security:
        - {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accesstoken:
                    type: string
                    format: binary
                    example: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSld...
        '401':
          $ref: '#/components/responses/LoginFailed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /validate/document:
    post:
      operationId: postValidateDocument
      tags:
        - Validation
      summary: Validate a digitally signed content
      description: |-
        Validate signatures in digitally signed content, such as a PDF or XML file.
        A validation ID {id} is returned that can be used to call additional
        endpoints. The content to be validated is provided in the request body and
        is not retained within our service. The maximum request or file size is
        50MB. Request parameters can be used to set optional parameters to control
        the validation
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/quality'
        - $ref: '#/components/parameters/preservation'
        - $ref: '#/components/parameters/legislation'
        - $ref: '#/components/parameters/additionalInfos'
        - $ref: '#/components/parameters/rejectVisualDifferences'
        - $ref: '#/components/parameters/rejectUndefinedChanges'
      requestBody:
        description: Content can be sent directly as a file or base64-encoded in a JSON object
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: binary
                  description: File content to validate (PDF or XML)
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: base64
                  description: Base64-encoded content of the document to validate
                  example: MIICjDCCAfWgAwIBAgIJANJczGLGyD...
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentValidationResponse'
              examples:
                Default:
                  $ref: '#/components/examples/DocumentValidation'
                WithSigners:
                  $ref: '#/components/examples/DocumentValidationWithSigner'
                WithFormatAndDetails:
                  $ref: '#/components/examples/DocumentValidationWithFormat'
                DocumentValidationWithFormat:
                  $ref: '#/components/examples/DocumentValidationWithChecks'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '413':
          $ref: '#/components/responses/ContentTooLarge'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /validate/signature:
    post:
      operationId: postValidateSignature
      tags:
        - Validation
      summary: Validate a digital signature
      description: |-
        Validate digital signatures such as CMS and CAdES without providing the
        associated signed content. A validation ID {id} is returned that can be used
        to call additional endpoints. The signature to be validated is provided in
        the request body. Query parameters can be used to set optional parameters to
        control the validation.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/quality'
        - $ref: '#/components/parameters/preservation'
        - $ref: '#/components/parameters/legislation'
        - $ref: '#/components/parameters/additionalInfos'
      requestBody:
        description: Content can be sent directly as a file or base64-encoded in a JSON object
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: binary
                  description: File content to validate (PDF or XML)
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: base64
                  description: Base64-encoded content of the document to validate
                  example: MIICjDCCAfWgAwIBAgIJANJczGLGyD...
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignatureValidationResponse'
              examples:
                Default:
                  $ref: '#/components/examples/SignatureValidation'
                WithSigners:
                  $ref: '#/components/examples/SignatureValidationWithSigner'
                WithFormatAndDetails:
                  $ref: '#/components/examples/SignatureValidationWithFormat'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /validate/certificate:
    post:
      operationId: postValidateCertificate
      tags:
        - Validation
      summary: Validate a digital certificate [ROADMAP]
      description: |-
        Validate a digital certificate outside of its use within signatures. A
        validation ID {id} is returned that can be used to call additional
        endpoints. The content to be validated is provided in the request body.
      security:
        - bearerAuth: []
      requestBody:
        description: Content can be sent directly as a file or base64-encoded in a JSON object
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: binary
                  description: File content to validate (PDF or XML)
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: base64
                  description: Base64-encoded content of the document to validate
                  example: MIICjDCCAfWgAwIBAgIJANJczGLGyD...
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateValidationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '501':
          $ref: '#/components/responses/NotImplemented'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /validate/{id}:
    delete:
      operationId: deleteValidation
      tags:
        - Validation
      summary: Deletes the validation
      description: |-
        Deletes the corresponding resource identified by {id}, universal for all
        validation resources. Any resource that is not manually deleted will be
        automatically deleted after 10 minutes.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/validateid'
      responses:
        '204':
          $ref: '#/components/responses/Success'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /infos/{id}/validation:
    get:
      operationId: getInfosValidation
      tags:
        - Additional Information
      summary: Get additional information about the validation itself. Refer to ETSI EN 319 102-1 for the indications and sub-indications that may be encountered.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/validateid'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationInfosResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '429':
          description: Too many requests
        '500':
          description: Internal Server Error
        '503':
          description: Service unavailable
  /infos/{id}/signers:
    get:
      operationId: getInfosSigners
      tags:
        - Additional Information
      summary: Get additional information about the signers of a validation
      description: |-
        Additional information about the people who signed the document. The query
        parameter is the id from the validation endpoint.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/validateid'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignerInfosResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /infos/{id}/format:
    get:
      operationId: getInfosFormat
      tags:
        - Additional Information
      summary: Get additional information about the document format
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/validateid'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormatInfosResponse'
              examples:
                PDF:
                  $ref: '#/components/examples/FormatPDF'
                XML:
                  $ref: '#/components/examples/FormatXML'
                CMS:
                  $ref: '#/components/examples/FormatCMS'
                PDFA:
                  $ref: '#/components/examples/FormatPDFA'
        '400':
          $ref: '#/components/responses/ServiceUnavailable'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /reports/{id}/skribble:
    get:
      operationId: getReportsSkribble
      tags:
        - Reports
      summary: Skribble validation report [ROADMAP]
      description: Get the digitally signed Skribble validation report as PDF
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/validateid'
      responses:
        '200':
          description: Success
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '429':
          description: Too many requests
        '500':
          description: Internal Server Error
        '501':
          description: Not implemented
        '503':
          description: Service unavailable
  /reports/{id}/etsi:
    get:
      operationId: getReportsETSI
      tags:
        - Reports
      summary: ETSI TS 119 102-2 validation report
      description: Get the ETSI TS 119 102-2 signature validation report as a XML
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/validateid'
      responses:
        '200':
          description: Success
          content:
            application/xml:
              schema:
                type: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '429':
          description: Too many requests
        '500':
          description: Internal Server Error
        '503':
          description: Service unavailable
  /tooling/upload:
    post:
      operationId: postToolingUpload
      tags:
        - Tooling
      summary: Upload document for processing
      description: |-
        Upload a document to be used in the tooling process. A process ID {id} is
        returned which can be used to call additional endpoints. If not already a
        PDF, the uploaded document will be converted into one. The maximum request
        or file size is 50MB.
      security:
        - bearerAuth: []
      requestBody:
        description: Content can be sent directly as a file or base64-encoded in a JSON object
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: binary
                  description: File content to upload for tooling processing
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  format: base64
                  description: Base64-encoded content of the document to upload
                  example: MIICjDCCAfWgAwIBAgIJANJczGLGyD...
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolingUploadResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '413':
          $ref: '#/components/responses/ContentTooLarge'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /tooling/process/{id}/check:
    post:
      operationId: postToolingProcessCheck
      tags:
        - Tooling
      summary: Check document PDF conformance
      description: |-
        Checks the document against a specific set of PDF conformance criteria and
        guidelines. Can be called multiple times to get current status and results;
        if relevant changes have been made to the document with other tools, it will
        process the document again. If the status '423 Locked' is returned it can be
        recalled with some delay.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/uploadid'
        - $ref: '#/components/parameters/conformanceCheck'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolingCheckResponse'
              examples:
                Success:
                  $ref: '#/components/examples/ToolingSuccessCheck'
                Failed:
                  $ref: '#/components/examples/ToolingFailedCheck'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '423':
          $ref: '#/components/responses/Locked'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /tooling/process/{id}/conform:
    post:
      operationId: postToolingProcessConform
      tags:
        - Tooling
      summary: Conform document
      description: |-
        Convert the document to a specific PDF conformance. Can be called multiple
        times to get current status and results; if relevant changes have been made
        to the document with other tools, it will process the document again. If the
        process status is 'pending', '423 Locked' is returned and it can be recalled
        with some delay.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/uploadid'
        - $ref: '#/components/parameters/conformanceConform'
        - $ref: '#/components/parameters/allowDowngrade'
        - $ref: '#/components/parameters/force'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolingConformResponse'
              examples:
                Success:
                  $ref: '#/components/examples/ToolingSuccessConform'
                Downgraded:
                  $ref: '#/components/examples/ToolingSuccessConformDown'
                Failed:
                  $ref: '#/components/examples/ToolingFailed'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '423':
          $ref: '#/components/responses/Locked'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /tooling/process/{id}/compress:
    post:
      operationId: postToolingProcessCompress
      tags:
        - Tooling
      summary: Compress document
      description: |-
        Compress the document for a specific purpose. For best size and compliance,
        this should be done before any /convert. Can be called multiple times to get
        current status and results; if relevant changes have been made to the
        document with other tools, it will process the document again. If '423
        Locked' is returned it can be recalled with some delay.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/uploadid'
        - $ref: '#/components/parameters/optimisation'
        - $ref: '#/components/parameters/force'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolingCompressResponse'
              examples:
                Success:
                  $ref: '#/components/examples/ToolingSuccessCompress'
                Failed:
                  $ref: '#/components/examples/ToolingFailed'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '423':
          $ref: '#/components/responses/Locked'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /tooling/process/{id}/spotsigners:
    post:
      operationId: postToolingProcessSpotSigners
      tags:
        - Tooling
      summary: Spot document for signature relevant elements
      description: |-
        Spots and detects document elements such as fields, signatures, and
        positions using tags and artificial intelligence. After detection, the
        document is updated and fields and tags are removed while maintaining
        current PDF compliance. Can be called multiple times to get current status
        and results; if relevant changes have been made to the document with other
        tools, it will process the document again. If the process status is
        'pending', '423 Locked' is returned and it can be recalled with some delay.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/uploadid'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolingSpotResponse'
              examples:
                Success:
                  $ref: '#/components/examples/ToolingSuccessSpot'
                Pending:
                  $ref: '#/components/examples/ToolingSpotPending'
                Failed:
                  $ref: '#/components/examples/ToolingSpotFailed'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '423':
          $ref: '#/components/responses/Locked'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '501':
          $ref: '#/components/responses/NotImplemented'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /tooling/{id}:
    get:
      operationId: getToolingID
      tags:
        - Tooling
      summary: Download processed document
      description: |-
        Download the processed document with the changes and enhancements made
        according to the specified processing steps. If the status '423 Locked' is
        returned it can be recalled with some delay.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/uploadid'
      responses:
        '200':
          description: Success
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '423':
          $ref: '#/components/responses/Locked'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
    delete:
      operationId: deleteToolingID
      tags:
        - Tooling
      summary: Delete processed document
      description: |-
        Terminates all running processes on the document and deletes all associated
        content. This action occurs automatically after 10 minutes if not explicitly
        invoked.
      security:
        - {}
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/uploadid'
      responses:
        '204':
          $ref: '#/components/responses/Success'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /billing/credits/infos:
    get:
      operationId: getBillingCreditsInfos
      tags:
        - Billing and Credits
      summary: Credits information
      description: Get the list of credit usage information associated with specific endpoints
      security:
        - {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingCreditInfos'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /billing/credits/usage:
    get:
      operationId: getBillingCreditsUsage
      tags:
        - Billing and Credits
      summary: Current credit usage
      description: Get credit usage list and details for current billing period
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingCreditUsage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
  /billing/credits/invoiced:
    get:
      operationId: getBillingCreditsInvoiced
      tags:
        - Billing and Credits
      summary: Invoiced credit details
      description: |-
        Get invoiced credit details for the most recent billing period or a
        specified time period
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: period
          schema:
            type: string
          description: |-
            Format YYYY, YYYYMM, YYYYMMDD is supported. If not specified the last
            invoiced period is used by default
          required: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingCreditUsage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      required:
        - apikey
        - username
      properties:
        username:
          type: string
          example: Customer_A
          description: The username of the users credentials to login
        apikey:
          type: string
          example: 00000000-0000-0000-0000-000000000000
          description: The API key  of the users credentials to login
    SignerCertificate:
      type: object
      properties:
        subject:
          type: string
          example: CN=John Doe, C=CH, SerialNumber=RAS64084aeaf178c31a
        issuer:
          type: string
          example: CN=Swisscom Diamant CA 4, OU=Digital Certificate Services, O=Swisscom (Schweiz) AG, C=ch
        serialNumber:
          type: string
          example: '160038991315232382650416191585425640265'
    OptionalSignerInfos:
      type: object
      properties:
        name:
          type: string
          example: John Doe
        contact:
          type: string
          example: john.doe@acme.org
        location:
          type: string
          example: Zurich, Switzerland
        reason:
          type: string
          example: john.doe@acme.org digitally signed on skribble.com
    Signer:
      type: object
      properties:
        valid:
          type: boolean
          example: true
        signer:
          type: string
          example: john.doe@acme.org
        time:
          type: string
          format: date-time
          example: '2018-11-28T11:51:58.637Z'
        quality:
          type: string
          example: QES
        legislation:
          type: string
          example: CH
        longTermValidation:
          type: boolean
          example: true
        visualDifferences:
          type: boolean
          example: true
        undefinedChanges:
          type: boolean
          example: true
        certificate:
          $ref: '#/components/schemas/SignerCertificate'
        optionalInfos:
          $ref: '#/components/schemas/OptionalSignerInfos'
    SignerInfosResponse:
      type: array
      items:
        $ref: '#/components/schemas/Signer'
    FormatInfosResponse:
      type: object
      properties:
        fileType:
          type: string
          description: File Type
        quality:
          type: string
          description: (Optional) File Type Quality
        producer:
          type: string
          description: (Optional) File producer
    ValidationInfosResponse:
      type: object
      properties:
        indication:
          type: string
          example: TOTAL-FAILED
        subIndication:
          type: string
          example: HASH_FAILURE
        details:
          type: array
          items:
            type: string
          example:
            - The certificate validation is not conclusive!
            - The current time is not in the validity range of the signer's certificate!
            - The signature is not intact!
    OptionalValidationInfos:
      type: object
      properties:
        signer:
          $ref: '#/components/schemas/SignerInfosResponse'
        format:
          $ref: '#/components/schemas/FormatInfosResponse'
        validation:
          $ref: '#/components/schemas/ValidationInfosResponse'
    DocumentValidationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        valid:
          type: boolean
          example: true
        signatures:
          type: integer
          description: Number of signatures found
          example: 1
        validSignatures:
          type: integer
          description: Number of valid signatures found
          example: 1
        quality:
          type: string
          description: Highest signature quality found
          example: QES
        legislation:
          type: string
          description: Identified legislation (CH, EU, CH-EU, WORLD)
          example: CH
        longTermValidation:
          type: boolean
          description: All signatures are provided with long-term validation information
          example: true
        visualDifferences:
          type: boolean
          description: Indicates if visual differences were detected
          example: true
        undefinedChanges:
          type: boolean
          description: Indicates if undefined changes were detected
          example: false
        additionalInfos:
          description: (Optional) Additional information details
          $ref: '#/components/schemas/OptionalValidationInfos'
    SignatureValidationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        valid:
          type: boolean
          example: true
        signatures:
          type: integer
          description: Number of signatures found
          example: 1
        validSignatures:
          type: integer
          description: Number of valid signatures found
          example: 1
        quality:
          type: string
          description: Highest signature quality found
          example: QES
        legislation:
          type: string
          description: Identified legislation (CH, EU, CH-EU, WORLD)
          example: CH
        longTermValidation:
          type: boolean
          description: All signatures are provided with long-term validation information
          example: true
        additionalInfos:
          description: (Optional) Additional information details
          $ref: '#/components/schemas/OptionalValidationInfos'
    CertificateValidationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        valid:
          type: boolean
          example: true
    ToolingUploadResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Universally Unique Identifier (UUID) for the related resource
          example: 1cbd5761-1429-437d-89c1-d8eacc49bf36
        name:
          type: string
          description: Filename of the uploaded document
          example: Sample File.pdf
        properties:
          type: object
          description: Additional details and properties of the document
          properties:
            sha1:
              type: string
              description: Cryptographic hash
              example: 5e13ae4640ae4ae0e09c05b7bb060f544dabd042
            size:
              type: integer
              description: Filesize in bytes
              example: 123456
            pages:
              type: integer
              description: Number of pages in file
              example: 3
            creation:
              type: string
              format: date-time
              description: File creation date
              example: '2024-05-30T13:45:00Z'
            modification:
              type: string
              format: date-time
              description: File modification date
              example: '2024-06-08T15:47:00Z'
            claimedConformance:
              type: string
              description: Claimed PDF conformance
              example: pdf-1.7
        permissions:
          type: object
          description: Permissions of the document
          properties:
            canConform:
              type: boolean
              description: Can be conformed
            canCompress:
              type: boolean
              description: Can be compressed
            allowsSign:
              type: boolean
              description: Allows digital signing
            allowsAnnotate:
              type: boolean
              description: Allows annotations
            allowsFill:
              type: boolean
              description: Allows filling of form fields
            allowsModify:
              type: boolean
              description: Allows changing the document
        metadata:
          type: object
          description: Metadata of the document
          properties:
            author:
              type: string
              example: Document author
            creator:
              type: string
              example: Document creator
            producer:
              type: string
              example: Document producer
            subject:
              type: string
              example: Document subject
            title:
              type: string
              example: Document title
            keywords:
              type: array
              items:
                type: string
              example:
                - Keyword1
                - Keyword2
    ProcessStatus:
      type: string
      description: Process Status
      items:
        type: string
        enum:
          - success
          - failed
      example: success
    ProcessDetails:
      type: array
      description: Additional details
      items:
        type: string
      example:
        - Warnings occured during PDF/A conversion
        - Cannot convert file to PDF/A
    ToolingCheckResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ProcessStatus'
        conformance:
          type: string
          description: PDF conformance
        claimedConformance:
          type: string
          description: Claimed PDF conformance
        recommendedConformance:
          type: string
          description: Recommended (highest possible) conformance for conform endpoint
        details:
          $ref: '#/components/schemas/ProcessDetails'
    ToolingConformResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ProcessStatus'
        conformance:
          type: string
          description: PDF conformance
        downgraded:
          type: boolean
          description: Has a conformance downgrade
        claimedConformance:
          type: string
          description: Claimed PDF conformance
        details:
          $ref: '#/components/schemas/ProcessDetails'
    ToolingCompressResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ProcessStatus'
        optimisation:
          type: string
          description: PDF Optimisation
        claimedConformance:
          type: string
          description: Claimed PDF conformance
        pages:
          type: integer
          description: Number of pages
        originalSize:
          type: integer
          description: Original size in Bytes
        newSize:
          type: integer
          description: New size in Bytes
        compressionRatio:
          type: number
          description: Compression ratio
        spaceSaving:
          type: number
          description: Space saving
        details:
          $ref: '#/components/schemas/ProcessDetails'
    ProcessStatusSpot:
      type: string
      description: Process Status
      items:
        type: string
        enum:
          - success
          - pending
          - failed
      example: success
    ToolingSpotResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ProcessStatusSpot'
        results:
          type: object
          properties:
            quality:
              type: string
              description: Spoted signature quality
            legislation:
              type: string
              description: Spoted legislation
            signers:
              type: array
              description: Spoted signers
              items:
                type: object
                properties:
                  signer:
                    type: string
                    description: Signer unique name and id
                  email:
                    type: string
                    description: Signer eMail (optional)
                  sequence:
                    type: integer
                    description: Sequence in signing (optional)
            signatures:
              type: array
              description: Spoted signature fields
              items:
                type: object
                properties:
                  signer:
                    type: string
                    description: Signer unique name and id (optional)
                  positions:
                    type: array
                    description: Signature Positions (optional)
                    items:
                      type: object
                      properties:
                        page:
                          type: integer
                          description: Page number
                        height:
                          type: number
                          description: Height of signature
                        width:
                          type: number
                          description: Width of signature
                        x:
                          type: number
                          description: X coordinate from the bottom of signature
                        'y':
                          type: number
                          description: Y coordinate from the bottom of signature
            observers:
              type: array
              description: Spoted observers
              items:
                type: string
        details:
          $ref: '#/components/schemas/ProcessDetails'
    CreditInfo:
      type: object
      properties:
        sku:
          type: string
          description: SKU of the API endpoint
          example: 01-01
        endpoint:
          type: string
          description: API endpoint
          example: /validate/document
        credits:
          type: integer
          description: Credit usage per successful API endpoint call
          example: 2
    BillingCreditInfos:
      type: object
      properties:
        validFrom:
          type: string
          format: date-time
          description: ISO 8601 date-time in UTC
          example: '2024-05-30T13:45:00Z'
        consumptions:
          type: array
          description: Array of consumptions, each with endpoint details and its credit cost
          items:
            $ref: '#/components/schemas/CreditInfo'
    CreditUsage:
      type: object
      properties:
        endpoint:
          type: string
          description: The API endpoint being consumed
          example: /validate/document
        requests:
          type: integer
          description: Number of credits consumed by the endpoint call
          example: 2
        credits:
          type: integer
          description: The number of credits consumed through the corresponding endpoint
          example: 4
    BillingCreditUsage:
      type: object
      properties:
        period:
          type: string
          description: Billing period in YYYYMM format
          example: '20240528'
        usage:
          type: array
          description: Array of consumptions, each detailing an endpoint use and its credit usage
          items:
            $ref: '#/components/schemas/CreditUsage'
        requests:
          type: integer
          description: Total of requests made
          example: 2
        credits:
          type: integer
          description: Total of credits used
          example: 4
  responses:
    LoginFailed:
      description: Login failed
    TooManyRequests:
      description: Too many requests
    ServerError:
      description: Internal server error
    ServiceUnavailable:
      description: Service unavailable
    BadRequest:
      description: Bad request
    Unauthorized:
      description: Unauthorized
    ContentTooLarge:
      description: Content too large
    NotImplemented:
      description: Not implemented
    Success:
      description: Success
    NotFound:
      description: Not found
    UnsupportedMediaType:
      description: Unsupported Media Type
    Locked:
      description: Locked
  parameters:
    quality:
      name: quality
      required: false
      in: query
      description: |-
        Optional flag specifying the minimum signature quality required (SES, AES,
        QES).
      schema:
        type: string
        enum:
          - SES
          - AES
          - QES
    preservation:
      name: longTermValidation
      in: query
      required: false
      description: Optional flag indicating whether the signature must be long-term valid.
      schema:
        type: boolean
    legislation:
      name: legislation
      in: query
      required: false
      description: |-
        Optional flag specifying the legislation to comply with (WORLD, CH, EU,
        CH_EU).
      schema:
        type: string
        enum:
          - WORLD
          - CH
          - EU
          - CH_EU
    additionalInfos:
      name: infos
      in: query
      required: false
      description: |-
        Optional flag to request additional information, such as validation, format,
        or signer details.
      schema:
        type: array
        items:
          type: string
          enum:
            - validation
            - format
            - signer
    rejectVisualDifferences:
      name: rejectVisualDifferences
      in: query
      required: false
      description: |-
        Optional flag to specify if visual differences should be rejected. If 'true',
        validation will fail due to visual differences; if 'false' or not provided,
        visual differences will not cause validation to fail.
      schema:
        type: boolean
    rejectUndefinedChanges:
      name: rejectUndefinedChanges
      in: query
      required: false
      description: |-
        Optional flag to specify if undefined changes should be rejected. If 'true',
        validation will fail due to undefined changes; if 'false' or not provided,
        undefined changes will not cause validation to fail.
      schema:
        type: boolean
    validateid:
      name: id
      in: path
      required: true
      description: The 'id' provided by the validate operation
      schema:
        type: string
        format: uuid
        default: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    uploadid:
      name: id
      in: path
      required: true
      description: The 'id' provided by the tooling upload operation
      schema:
        type: string
        format: uuid
        default: 1cbd5761-1429-437d-89c1-d8eacc49bf36
    conformanceCheck:
      name: conform
      in: query
      required: true
      description: PDF Conformance
      schema:
        type: string
        enum:
          - claimed
          - pdfa-1b
          - pdfa-1a
          - pdfa-2b
          - pdfa-2u
          - pdfa-2a
          - pdfa-3b
          - pdfa-3u
          - pdfa-3a
        default: claimed
    conformanceConform:
      name: conform
      in: query
      required: true
      description: PDF Conformance
      schema:
        type: string
        enum:
          - recommendedConformance
          - pdfa-1b
          - pdfa-1a
          - pdfa-2b
          - pdfa-2u
          - pdfa-2a
          - pdfa-3b
          - pdfa-3u
          - pdfa-3a
        default: recommendedConformance
    allowDowngrade:
      name: allowdowngrade
      in: query
      required: true
      description: Allows conformance downgrade in case of conversion error
      schema:
        type: boolean
        default: true
    force:
      name: force
      in: query
      required: false
      description: Forces process despite canConvert or canCompress state
      schema:
        type: boolean
    optimisation:
      name: optimise
      in: query
      required: true
      description: PDF Optimisation
      schema:
        type: string
        enum:
          - archive
          - print
          - size
          - web
        default: size
  examples:
    DocumentValidation:
      summary: Standard validation
      value:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        valid: true
        signatures: 1
        validSignatures: 1
        quality: QES
        legislation: CH
        longTermValidation: true
        visualDifferences: false
        undefinedChanges: false
    DocumentValidationWithSigner:
      summary: With signer
      value:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        valid: true
        signatures: 1
        validSignatures: 1
        quality: QES
        legislation: CH
        longTermValidation: true
        visualDifferences: false
        undefinedChanges: false
        additionalInfos:
          signer:
            - valid: true
              signer: John Doe
              time: '2018-11-28T11:51:58.637Z'
              quality: QES
              legislation: CH
              longTermValidation: true
              visualDifferences: false
              undefinedChanges: false
              certificate:
                subject: CN=John Doe, C=CH, SerialNumber=RAS64084aeaf178c31a
                issuer: CN=Swisscom Diamant CA 4, OU=Digital Certificate Services, O=Swisscom (Schweiz) AG, C=ch
                serialNumber: '160038991315232382650416191585425640265'
              optionalInfos:
                name: John Doe
                contact: john.doe@acme.org
    DocumentValidationWithFormat:
      summary: With format and validation
      value:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        valid: true
        signatures: 1
        validSignatures: 1
        quality: QES
        legislation: CH
        longTermValidation: true
        visualDifferences: false
        undefinedChanges: false
        additionalInfos:
          format:
            fileType: PDF
            producer: Acrobat Distiller 6.0 (Windows)
          validation:
            indication: TOTAL-PASSED
    DocumentValidationWithChecks:
      summary: Rejected visual differences
      value:
        id: 9c2d7b48-4e1f-4d37-91e5-7bdfc9a9e3f1
        valid: false
        signatures: 1
        validSignatures: 1
        quality: SES
        legislation: CH
        longTermValidation: true
        visualDifferences: true
        undefinedChanges: false
    SignatureValidation:
      summary: Standard validation
      value:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        valid: true
        signatures: 1
        validSignatures: 1
        quality: QES
        legislation: CH
        longTermValidation: true
    SignatureValidationWithSigner:
      summary: With signer
      value:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        valid: true
        signatures: 1
        validSignatures: 1
        quality: QES
        legislation: CH
        longTermValidation: true
        additionalInfos:
          signer:
            - valid: true
              signer: John Doe
              time: '2018-11-28T11:51:58.637Z'
              quality: QES
              legislation: CH
              longTermValidation: true
              certificate:
                subject: CN=John Doe, C=CH, SerialNumber=RAS64084aeaf178c31a
                issuer: CN=Swisscom Diamant CA 4, OU=Digital Certificate Services, O=Swisscom (Schweiz) AG, C=ch
                serialNumber: '160038991315232382650416191585425640265'
              optionalInfos:
                name: John Doe
                contact: john.doe@acme.org
    SignatureValidationWithFormat:
      summary: With format and validation
      value:
        id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        valid: true
        signatures: 1
        validSignatures: 1
        quality: QES
        legislation: CH
        longTermValidation: true
        additionalInfos:
          format:
            fileType: CMS
            producer: ''
          validation:
            indication: TOTAL-PASSED
    FormatPDF:
      summary: Sample PDF/PAdES
      value:
        fileType: PDF
        producer: Acrobat Distiller 6.0 (Windows)
    FormatXML:
      summary: Sample XML/XAdES
      value:
        fileType: XML
    FormatCMS:
      summary: Sample CMS/CAdES
      value:
        fileType: CMS
    FormatPDFA:
      summary: Sample PDF/A
      value:
        fileType: PDF
        quality: PDF/A-2A
        producer: Acrobat Distiller 6.0 (Windows)
    ToolingSuccessCheck:
      summary: Processed
      value:
        status: success
        conformance: pdfa-2b
        claimedConformance: pdfa-2b
        recommendedConformance: pdfa-3a
    ToolingFailedCheck:
      summary: Failed
      value:
        status: failed
        claimedConformance: pdfa-2b
        details:
          - '- FONT: The value of the CIDSet[67] of font EAAAAB+OpenSans-Regular is false but must be true'
    ToolingSuccessConform:
      summary: Processed
      value:
        status: success
        conformance: pdfa-3a
        downgraded: false
        claimedConformance: pdfa-2b
    ToolingSuccessConformDown:
      summary: Downgraded
      value:
        status: success
        conformance: pdfa-1b
        downgraded: true
        claimedConformance: pdfa-2b
    ToolingFailed:
      summary: Process has failed
      value:
        status: failed
        details:
          - '- FONT: The value of the CIDSet[67] of font EAAAAB+OpenSans-Regular is false but must be true'
    ToolingSuccessCompress:
      summary: Processed
      value:
        status: success
        optimisation: size
        claimedConformance: pdf-1.5
        pages: 12
        originalSize: 907128
        newSize: 228161
        compressionRatio: 3.975824
        spaceSaving: 0.7484798176
    ToolingSuccessSpot:
      summary: Processed
      value:
        status: success
        results:
          quality: QES
          legislation: CH
          signers:
            - signer: John Doe
              email: john.doe@acme.org
              sequence: 1
            - signer: Jane Doe
              email: jane.doe@acme.org
              sequence: 2
          signatures:
            - signer: John Doe
              positions:
                - page: 0
                  height: 70
                  width: 150
                  x: 350
                  'y': 240
            - signer: Jane Doe
              positions:
                - page: 0
                  height: 70
                  width: 150
                  x: 500
                  'y': 240
          observers:
            - backoffice@acme.org
    ToolingSpotPending:
      summary: Process is pending
      value:
        status: pending
    ToolingSpotFailed:
      summary: Spot has failed
      value:
        status: failed
        details:
          - PDF is password protected
